###
// Get All News
GET http://localhost:5000/news
Content-Type: application/json


###
// POST Data news
POST  http://localhost:5000/news
Content-Type: application/json

{
    "title": "Jokowi soal Mudik: Semua Sudah Diatur, Insyaallah Tak Ada Masalah",
    "content": "<p>Presiden Joko Widodo menyampaikan pemerintah telah melakukan perbaikan manajemen agar mudik Lebaran 2023 berjalan lancar. Jokowi berharap tak ada masalah signifikan saat arus mudik tahun ini.</p>",
    "imageUrl": "https://akcdn.detik.net.id/community/media/visual/2023/03/31/presiden-jokowi-meresmikan-kek-lido-di-bogor_169.png?w=700&q=90"
    
}

###
// Edit Data news
PATCH   http://localhost:5000/news/4c8f6575-bc03-4c3c-8a94-7c28a6a27551
Content-Type: application/json

{
    "title": "Kakorlantas Ingatkan Tol Cikampek Km 47 Jadi Titik Contraflow",
    "content": "ohanis Tanak: mengatakan percakapan via aplikasi perpesanan antara dirinya dan Plh Dirjen Minerba Kementerian ESDM Muhammad Idris Froyoto Sihite terjadi sebelum dirinya menjabat Wakil Ketua KPK. Begini <em>timeline</em> pengusulan hingga pengambilan sumpah Johanis Tanak sebagai Wakil Ketua KPK.",
    "imageUrl": "https://akcdn.detik.net.id/community/media/visual/2023/04/12/rizky-adha-mahendradetikcom_169.jpeg?w=700&q=90"
    
}